name    'fraenki-vpasswd'
version '0.1.1'
source 'git://github.com/fraenki/puppet-vpasswd'
author 'Frank Wall'
license 'Simplified BSD License'
summary 'Manage virtual users'
description 'This module manages virtual users and creates passwd-like files.'
project_page 'https://github.com/fraenki/puppet-vpasswd'

dependency 'puppetlabs/concat', '>= 1.1.0'
dependency 'puppetlabs/stdlib', '>= 4.0.0'
